steps:
  - id: Build/push to AR
    name: quay.io/buildah/stable:latest
    entrypoint: bash
    args:
      - -c
      - |
        buildah build \
          --tag $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
          --tag $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest \
          --file ./Dockerfile \
          --format docker \
          --layers \
          --cache-from $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME/cache \
          --cache-to $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME/cache \
          .

        buildah push \
          $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
        buildah push \
          $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest

  - id: Deploy to Cloud Run
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    secretEnv:
      - POSTGRES_CONNECTION_STRING
      - SUPABASE_JWT_SECRET
    entrypoint: bash
    args:
      - -ceu
      - |
        gcloud run services update $_SERVICE_NAME \
          --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
          --region=$_DEPLOY_REGION \
          --quiet \
          --service-account=$_SERVICE_ACCOUNT \
          --set-env-vars \
          "POSTGRES_CONNECTION_STRING=$$POSTGRES_CONNECTION_STRING,SUPABASE_JWT_SECRET=$$SUPABASE_JWT_SECRET,GIN_MODE=$_GIN_MODE,SERVICE_ACCOUNT_EMAIL=$_USER_SERVICE_ACCOUNT_EMAIL,AR_REPO_URL=$_USER_AR_REPO_URL,GCP_PROJECT_ID=$_AR_PROJECT_ID,GCP_REGION=$_DEPLOY_REGION"

serviceAccount: projects/local-first-476300/serviceAccounts/cloud-build-sa@local-first-476300.iam.gserviceaccount.com

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: controller-0p5dev
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_REPOSITORY: open-source-application-images
  _AR_PROJECT_ID: local-first-476300
  _USER_AR_REPO_URL: us-central1-docker.pkg.dev/local-first-476300/container-images-dev
  _GIN_MODE: release
  _USER_SERVICE_ACCOUNT_EMAIL: user-service-sa-dev@local-first-476300.iam.gserviceaccount.com
  _CONTROLLER_SERVICE_ACCOUNT: controller-sa-staging@local-first-476300.iam.gserviceaccount.com

tags:
  - development
  - controller
  - vm

availableSecrets:
  secretManager:
    - versionName: projects/160851347747/secrets/supabase_connection_string_dev/versions/1
      env: "POSTGRES_CONNECTION_STRING"
    - versionName: projects/160851347747/secrets/supabase_jwt_secret_dev/versions/1
      env: "SUPABASE_JWT_SECRET"
