steps:
  - id: Retrieve service account key
    name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        SAKEY=$(gcloud secrets versions access latest --secret="ops-controller-sakey")
        echo "$$SAKEY" >> /workspace/sakey.json

  - id: Build/push to AR
    name: quay.io/buildah/stable:latest
    entrypoint: bash
    args:
      - -c
      - |
        buildah build \
          --tag $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
          --tag $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest \
          --build-arg PULUMI_STATE_BUCKET=$_PULUMI_STATE_BUCKET \
          --file ./Dockerfile \
          --format docker \
          --layers \
          --cache-from $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME/cache \
          --cache-to $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME/cache \
          .

        buildah push \
          $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
        buildah push \
          $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest

  - id: Ensure controller vm is running
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - compute
      - instances
      - start
      - controller-dev
      - --zone=us-central1-f

  - id: Deploy to controller vm
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - compute
      - ssh
      - cloud-build-sa@controller-dev
      - --zone=us-central1-f
      - --command=docker compose -f /app/docker-compose.yml down --rmi all --remove-orphans || true && docker compose -f /app/docker-compose.yml up -d

serviceAccount: projects/local-first-476300/serviceAccounts/cloud-build-sa@local-first-476300.iam.gserviceaccount.com

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: controller
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_REPOSITORY: open-source-application-images
  _AR_PROJECT_ID: local-first-476300
  _PULUMI_STATE_BUCKET: lf-controller-pulumi-state-staging

tags:
  - development
  - controller
  - vm
