name: controller
networks:
  0p5dev:
    driver: bridge
    name: 0p5dev
services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: controller
    volumes:
      - ./:/app
      - ~/.config/gcloud/application_default_credentials.json:/app/adc.json:ro
    working_dir: /app
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
        required: false
    networks:
      - 0p5dev
    env_file:
      - .env
    environment:
      # Anything not specified here is a secret, and must be specified in the .env file, or be passed as an ENV var to the container at runtime.
      POSTGRES_CONNECTION_STRING: ${POSTGRES_CONNECTION_STRING}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      AR_REPO_URL: us-central1-docker.pkg.dev/local-first-476300/container-images-dev
      GCP_PROJECT_ID: local-first-476300
      GCP_REGION: us-central1
      GIN_MODE: debug
      SERVICE_ACCOUNT_EMAIL: user-service-sa-dev@local-first-476300.iam.gserviceaccount.com
      # This ENV var must NOT be specified in the production Cloud Run service's environment. That environment will use ADC for authentication, and if this ENV var is set, it will override ADC and cause authentication to fail.
      GOOGLE_APPLICATION_CREDENTIALS: /app/adc.json
    profiles:
      - dev
      - local

  postgres:
    image: postgres
    container_name: controller-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    profiles:
      - local
